services:
  ionic:
    build: .
    container_name: ionic
    ports:
      - "8100:8100"
      - "3000:3000"
      - "4200:4200"
    volumes:
      - node_modules:/app/node_modules
    develop:
      watch:
        # Se cambio codice sorgente, ricopia i file nel container
        - path: .
          target: /app
          action: sync

        # Se cambio package.json, ricostruisci l'immagine
        - path: ./package.json
          action: rebuild
        - path: ./package-lock.json
          action: rebuild
volumes:
  node_modules:



# docker compose build
# docker compose up --watch

# Per copiare i node_modules per Prettier
# Start-Process powershell -Verb runAs -ArgumentList "-NoProfile -Command docker cp ionic:/app/node_modules '$PWD\node_modules'"
# sudo docker cp ionic:/app/node_modules ./node_modules